server {
    listen 80 default_server;
    server_name localhost;

    gzip on;
    gzip_static on;

    root /usr/share/nginx/html/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}

